Repository codethink-cn/Inkar-Suki, pull requests merged in 2024-03, with the labels that each got.

#779 24点
  src/plugins/twenty_four/__init__.py
  src/plugins/twenty_four/process.py
Labels: size/L

#780 feat: 自动邀请功能添加了按钮快速操作
  src/__init__.py
  src/plugins/developer_tools/adopt_bot.py
  src/plugins/event_notice/__init__.py
  src/tools/utils/markdown.py
Labels: 已在计划, 功能提交

#781 fix: 3.10的语法在低版本出错的问题
  src/tools/utils/markdown.py
Labels: 漏洞反馈, 功能提交

#782 掷骰子
  src/plugins/dice/__init__.py
  src/plugins/dice/dice.py
Labels: 功能提交, size/XL
